name: Aggiorna Volley

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npx playwright install --with-deps

      - run: node scripts/scanCampionati.js

      - run: node scripts/extractGirone.js

      - run: node scripts/buildJson.js

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git diff --staged --quiet || git commit -m "Aggiornamento FIPAV"

          git push
