name: Aggiorna Volley

on:
  workflow_dispatch:
    inputs:
      stagione:
        description: "Stagione da aggiornare"
        required: true
        default: "ALL"
        type: choice
        options:
          - ALL
          - 2026-2027
          - 2025-2026
          - 2024-2025

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installa dipendenze
        run: npm install

      - name: Installa Playwright
        run: npx playwright install --with-deps

      - name: Verifica sintassi update.js
        run: node --check scripts/update.js

      - name: Determina stagione
        id: stagione
        run: |
          echo "stagione=${{ github.event.inputs.stagione }}" >> $GITHUB_OUTPUT

      - name: Aggiorna dati FIPAV
        run: |
          echo "Aggiorno stagione ${{ steps.stagione.outputs.stagione }}"
          node scripts/update.js "${{ steps.stagione.outputs.stagione }}"

      - name: Merge archivio
        run: node scripts/merge.js

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git diff --staged --quiet || git commit -m "Aggiornamento FIPAV ${{ steps.stagione.outputs.stagione }}"

          git push
