name: Aggiorna Volley

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installa dipendenze
        run: npm install

      - name: Installa Playwright
        run: npx playwright install --with-deps

      - name: Aggiorna dati
        run: node scripts/update.js

      - name: Commit
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git diff --staged --quiet || git commit -m "Aggiornamento FIPAV"

          git push
